### PR TITLE
add "generated-typescript-types" rule

### PR DESCRIPTION
**Pull request by natelindev**
* use typeParameters instead of typeArguments.
* updated foundImport logic since typescript does not have importKind.
* added ts-recommended and ts-strict

### CODE REVIEW

**Review by sibelius — APPROVED** [review]
should we have tests for this?

**Comment by llldar** [comment]
It's currently very much incomplete, I'll let you know when I consider it ready.

**Comment by reckter** [comment]
Hey any progress on this? :) Just stumbled upon this issue, and would love this lint rule!

**Comment by llldar** [comment]
sry I didn't have much time on this, anyone is welcomed to continue on my progress

**Comment by alloy** [comment]
#128 got merged, which has these changes and more

**Pull request merged**
